 # Copyright (c) 2016 Open Connectivity Foundation (OCF) and AllJoyn Open
 #    Source Project (AJOSP) Contributors and others.
 #
 #    SPDX-License-Identifier: Apache-2.0
 #
 #    All rights reserved. This program and the accompanying materials are
 #    made available under the terms of the Apache License, Version 2.0
 #    which accompanies this distribution, and is available at
 #    http://www.apache.org/licenses/LICENSE-2.0
 #
 #    Copyright 2016 Open Connectivity Foundation and Contributors to
 #    AllSeen Alliance. All rights reserved.
 #
 #    Permission to use, copy, modify, and/or distribute this software for
 #    any purpose with or without fee is hereby granted, provided that the
 #    above copyright notice and this permission notice appear in all
 #    copies.
 #
 #     THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL
 #     WARRANTIES WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED
 #     WARRANTIES OF MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE
 #     AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL
 #     DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR
 #     PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER
 #     TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
 #     PERFORMANCE OF THIS SOFTWARE.

import os

Import('env')

src_env = env.Clone()

src_env.Append(LIBS = ['m'])

src_env['srcs'] = []
src_env['interface_srcs'] = []

#src_env['srcs'] += Glob('*.c')
src_env['srcs'] += Glob('CdmControllee/*.c')
src_env['srcs'] += Glob('utils/*.c')

src_env['interface_srcs'] += Glob('interfaces/*.c')
src_env['interface_srcs'] += Glob('interfaces/operation/*.c')
src_env['interface_srcs'] += Glob('interfaces/environment/*.c')
src_env['interface_srcs'] += Glob('interfaces/input/*.c')
src_env['interface_srcs'] += Glob('interfaces/userinterfacesettings/*.c')

# Compile sources and create libraries
objs = src_env.StaticObject(src_env['srcs'])
interface_objs = src_env.StaticObject(src_env['interface_srcs'])

lib = src_env.Library("ajtcl_cdm", objs)
interface_lib = src_env.Library("ajtcl_cdm_interfaces", interface_objs)

src_env.Install('#dist/lib', lib)
src_env.Install('#dist/lib', interface_lib)

if src_env['build_shared']:
    objs = src_env.SharedObject(src_env['srcs'])
    lib = src_env.SharedLibrary("ajtcl_cdm", objs)

    interface_objs = src_env.SharedObject(src_env['interface_srcs'])
    interface_lib = src_env.SharedLibrary("ajtcl_cdm_interfaces", interface_objs)

    src_env.Install('#dist/lib', lib)
    src_env.Install('#dist/lib', interface_lib)
